### ISSUE TITLE
install grafana plugins

### ISSUE THREAD

**Issue by ricardoklein** [hmmbug/ansible-grafana2#5]
I was using your grafana2 role (which is very good btw) but needed to install some plugins, so, I did this:

### in tasks/main.yml:
- name: Install grafana plugins
  shell: "grafana-cli plugins install {{ item }}"
  with_items: "{{ grafana_plugins }}"
  notify: Restart grafana

### In defaults/main.yml:
grafana_plugins: {}

### In host_vars (for the host I was setting up):
grafana_plugins:
  - grafana-plugin1
  - grafana-plugin2
...

considerations:
1 - Maybe we should have an "when" to only run if {{ grafana_plugins }} is not null, but, it works if you have it empty on defaults anyway.
2 - I know that using command/shell/raw modules are dirty, but, I am not sure I am able to built a module to do that in the right way.

ps.: I know I should open a pull/merge request, but, I dont know how to do that yet (I will learn soon... sorry).

**Comment by hmmbug** [comment]
Hi @kleinstuff, thanks for your feedback and update. I've made the changes you suggested in the issues5_plugins branch. Could you test it and confirm if it works correctly for you? I'll then merge it to master. Thanks!

**Comment by ricardoklein** [comment]
Hey @hmmbug, sorry for the delay (only had time to test now), it Worked like a charm!

### Setup vars:
      # hmmbug.grafana2
      grafana_plugins:
         - grafana-piechart-panel
         - jdbranham-diagram-panel
         - savantly-heatmap-panel
         - mtanda-histogram-panel
         - natel-plotly-panel

### Playbook Run:
     TASK [ansible-grafana2 : Install grafana plugins] ******************************
     changed: [testserver] => (item=grafana-piechart-panel)
     changed: [testserver] => (item=jdbranham-diagram-panel)
     changed: [testserver] => (item=savantly-heatmap-panel)
     changed: [testserver] => (item=mtanda-histogram-panel)
     changed: [testserver] => (item=natel-plotly-panel)

### Final check:
     [root@localhost ~]# grafana-cli plugins ls
     installed plugins:
     grafana-piechart-panel @ 1.1.4 
     jdbranham-diagram-panel @ 1.4.0 
     mtanda-histogram-panel @ 0.1.6 
     natel-plotly-panel @ 0.0.2 
     savantly-heatmap-panel @ 0.1.0 
     
     Restart grafana after installing plugins . <service grafana-server restart>

**Comment by hmmbug** [comment]
@kleinstuff thanks for testing! I've merged it to master.
